(()=>{'use strict';
const E=window.CampusScoring;
if(!E) throw new Error('CampusScoring v1.1 not loaded');
const DATA_URLS=['https://raw.githubusercontent.com/lizhenhai2024-alt/AI_Job/main/src/data/live-jobs.js','https://cdn.jsdelivr.net/gh/lizhenhai2024-alt/AI_Job@main/src/data/live-jobs.js'];
const STORAGE='campus-job-board:v1.1';
const STAGES=['已收藏','已投递','笔试','面试','Offer','淘汰'];
const LEVELS=['全部','S++','S','A','B','C','D','数据待修复'];
const fb=[{id:'fallback-1',company:'示例公司',title:'海外业务运营（2027届）',city:'深圳',graduationYear:'2027',roleFamily:['海外运营'],languages:['英语'],experienceKeywords:['海外业务','市场研究','客户信息'],preferenceTags:['国际业务','出海'],source:'回退示例',sourceType:'secondary',sourceUrl:'https://example.com/job',deadline:'2026-12-31',description:'实时岗位池不可用时的示例岗位，英语用于海外业务沟通。'}];
let persisted={};try{persisted=JSON.parse(localStorage.getItem(STORAGE)||localStorage.getItem('campus-job-board:original-restored')||localStorage.getItem('campus-job-board:v3')||'{}')}catch{}
const S={tab:'jobs',jobs:[],mode:'loading',updated:'',meta:{},filter:{q:'',level:'全部',direction:'全部',city:'全部',source:'全部',quality:'全部'},status:persisted.status||{},offers:persisted.offers||[],selected:null,limit:40};
const app=document.getElementById('app');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uniq=a=>[...new Set(a.filter(Boolean))];
const save=()=>localStorage.setItem(STORAGE,JSON.stringify({status:S.status,offers:S.offers}));
const levelClass=l=>l==='S++'||l==='S'?'s':l==='A'?'a':l==='B'?'b':'c';

function evaluated(){
  return S.jobs
    .filter(j=>String(j.graduationYear||'2027').includes('2027'))
    .map(j=>({...j,_evaluation:E.evaluate(j)}))
    .filter(j=>!E.isExpired(j.deadline))
    .sort(E.compare);
}
function normalJobs(){return evaluated().filter(j=>j._evaluation.gate.passed&&j._evaluation.dataQuality.status!=='INVALID')}
function filtered(){
  const f=S.filter,q=f.q.trim().toLowerCase();
  const pool=(f.level==='数据待修复'||f.quality==='INVALID')
    ? evaluated().filter(j=>j._evaluation.gate.passed&&j._evaluation.dataQuality.status==='INVALID')
    : normalJobs();
  return pool.filter(j=>{
    const ev=j._evaluation,hay=[j.company,j.title,j.city,ev.direction,...(j.skills||[])].join(' ').toLowerCase();
    const src=j.sourceType==='official'?'官方':'二手';
    return(!q||hay.includes(q))&&(f.level==='全部'||ev.level===f.level)&&(f.direction==='全部'||ev.direction===f.direction)&&(f.city==='全部'||j.city===f.city)&&(f.source==='全部'||src===f.source)&&(f.quality==='全部'||ev.dataQuality.status===f.quality);
  });
}
function updateBox(){return`<div class="update"><b><span class="dot ${S.mode==='live'?'':'warn'}"></span>${S.mode==='live'?'数据已更新':S.mode==='loading'?'正在读取岗位池':'回退数据模式'}</b><small>调研更新 ${S.updated?new Date(S.updated).toLocaleString('zh-CN',{hour12:false}):'—'}</small><small>评价规则 V1.1</small></div>`}
function nav(){const count=Object.keys(S.status).length;return`<div class="topbar"><div class="toprow"><div class="brand">2027届校招机会看板 · 英语专业</div><div class="nav">${[['jobs','机会看板'],['pipeline',`我的投递 ${count}`],['stats','统计分析'],['offers','Offer 对比']].map(([k,n])=>`<button data-tab="${k}" class="${S.tab===k?'active':''}">${n}</button>`).join('')}</div></div></div>`}
function shell(body){return`<div class="page">${nav()}${body}${modal()}</div>`}
function statBoxes(items){return`<div class="stats">${items.map(([v,l])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join('')}</div>`}
function qualityTag(q){return q.status==='VALID'?`<span class="tag ok">信息 ${q.score}/10 · VALID</span>`:q.status==='PARTIAL'?`<span class="tag warn">信息 ${q.score}/10 · 待核</span>`:`<span class="tag bad">信息 ${q.score}/10 · 待修复</span>`}
function jobCard(j){
  const v=j._evaluation, risk=v.risk.deduction, reason=v.level==='S++'?'强直接经历 + 高职责匹配':v.level==='S'?'核心方向高度匹配':v.level==='A'?'整体适配，值得重点投':v.level==='B'?'相邻机会，可选择性投':v.level==='C'?'探索机会，优先级较低':v.level==='D'?'投入产出比较低':v.level;
  return`<article class="card job"><div><div class="company">${esc(j.company||'待核公司')}</div><div class="jobtitle">${esc(j.title||'待核岗位')}</div><div class="meta"><span>📍 ${esc(j.city||'待核')}</span><span>🧭 ${esc(v.direction)}</span><span>🗓 ${esc(j.deadline||'待核')}</span><span>${esc(j.source||'来源待核')}</span></div><div class="tags"><span class="tag ${j.sourceType==='official'?'ok':'warn'}">${j.sourceType==='official'?'官方来源':'二手来源 · 投递前回官网'}</span>${qualityTag(v.dataQuality)}${risk?`<span class="tag warn">风险 -${risk}</span>`:''}</div></div><div class="match"><div><div class="level"><span class="pill ${levelClass(v.level)}">${esc(v.level)}</span> ${v.dataQuality.status!=='INVALID'?`<small>适配 ${v.fit.score}/100 · 优先 ${v.priorityScore}</small>`:''}</div><div class="matchreason">${esc(reason)}</div></div><div class="actions">${j.sourceUrl?`<a class="btn ${j.sourceType==='official'?'primary':'soft'}" target="_blank" rel="noopener" href="${esc(j.sourceUrl)}">${j.sourceType==='official'?'立即投递':'查看来源'}</a>`:''}<button class="btn" data-detail="${esc(j.id)}">评价详情</button><select class="status" data-status="${esc(j.id)}"><option value="">投递状态</option>${STAGES.map(x=>`<option ${S.status[j.id]===x?'selected':''}>${x}</option>`).join('')}</select></div></div></article>`
}
function jobsPage(){
  const all=evaluated(), normal=normalJobs(), list=filtered(), dirs=['全部',...uniq(normal.map(x=>x._evaluation.direction))],cities=['全部',...uniq(normal.map(x=>x.city))];
  const ss=normal.filter(x=>['S++','S'].includes(x._evaluation.level)).length,a=normal.filter(x=>x._evaluation.level==='A').length,partial=normal.filter(x=>x._evaluation.dataQuality.status==='PARTIAL').length,invalid=all.filter(x=>x._evaluation.gate.passed&&x._evaluation.dataQuality.status==='INVALID').length;
  return`<section class="hero"><div><h1>2027届校招机会看板</h1><div class="subtitle">湖南大学 · 英语专业 · CET-6 / TEM-4 ｜ 目标方向：GTM·市场策略 / PMO / 跨境电商运营 / 外贸海外业务 / HR·HRBP / 国际物流供应链管培</div></div>${updateBox()}</section>${statBoxes([[normal.length,'本科可投岗位'],[ss,'S++ / S'],[a,'A级'],[uniq(normal.map(x=>x._evaluation.direction)).length,'覆盖方向'],[partial,'待核岗位'],[invalid,'数据待修复']])}${S.mode==='fallback'?'<div class="notice">实时数据源暂不可用，当前显示回退样例。</div>':''}<div class="card filters filters6"><div class="field"><label>搜索</label><input id="q" value="${esc(S.filter.q)}" placeholder="公司 / 岗位 / 关键词"></div><div class="field"><label>等级</label><select id="level">${LEVELS.map(x=>`<option ${S.filter.level===x?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>方向</label><select id="direction">${dirs.map(x=>`<option ${S.filter.direction===x?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>城市</label><select id="city">${cities.map(x=>`<option ${S.filter.city===x?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>信息状态</label><select id="quality">${['全部','VALID','PARTIAL','INVALID'].map(x=>`<option ${S.filter.quality===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>来源</label><select id="source">${['全部','官方','二手'].map(x=>`<option ${S.filter.source===x?'selected':''}>${x}</option>`).join('')}</select></div><button id="reset" class="btn">重置</button></div><div class="ruleline"><div class="legend"><span class="pill s">S++ / S 核心优先</span><span class="pill a">A 重点投</span><span class="pill b">B 可尝试</span><span class="pill c">C / D 低优先</span></div><span class="muted">仅显示本科可投岗位；硕士/博士及其他硬门槛岗位默认排除</span></div><div class="summary"><b>共 ${list.length} 个岗位</b><span class="muted">按资格、数据质量、等级、优先分排序</span></div><div class="joblist">${list.slice(0,S.limit).map(jobCard).join('')||'<div class="card empty">没有符合当前筛选条件的岗位</div>'}</div>${list.length>S.limit?'<p style="text-align:center"><button class="btn" id="more">加载更多</button></p>':''}${dataNotes()}</section>`
}
function dataNotes(){return`<div class="card help"><h3>评价说明 · V1.1</h3><ul><li><b>AI_Job</b> 只负责发现、抓取、去重、来源核验与JD结构化；最终等级由本看板规则生成。</li><li><b>Eligibility Gate</b>：仅硕士/研究生、博士学历岗位，以及其他本科不满足的硬门槛岗位，直接从主看板排除；本科及以上、本科/硕士均可岗位保留。</li><li><b>Candidate Fit</b> = 职责30 + 专业语言20 + 真实经历25 + 职业方向15 + 可补足能力10。</li><li><b>Data Quality</b> 单独0–10，不进入适配分；INVALID岗位只进入数据修复队列。</li><li><b>风险</b> 单独扣分：长期驻外-15、高频出差-8、强销售KPI-10、高压-5等。</li><li>二手来源不降低候选人适配度，只降低信息可信度；投递前必须回企业官网核验。</li></ul></div>`}
function pipelinePage(){const all=evaluated(),selected=all.filter(j=>S.status[j.id]);return`<section class="hero"><div><h1>我的投递</h1><div class="subtitle">投递记录保存在当前浏览器，可导入导出备份。</div></div></section><div class="toolbar"><div class="actions"><button class="btn" id="export-json">导出 JSON</button><button class="btn" id="export-csv">导出 CSV</button><button class="btn" id="import-json">导入 JSON</button><input id="import-file" type="file" accept="application/json" class="hidden"></div><span class="muted">当前记录 ${selected.length} 个岗位</span></div><div class="pipeline">${STAGES.map(stage=>{const arr=selected.filter(j=>S.status[j.id]===stage);return`<div class="lane"><h3>${stage} · ${arr.length}</h3>${arr.map(j=>`<div class="mini" data-detail="${esc(j.id)}"><b>${esc(j.title)}</b><small>${esc(j.company)} · ${esc(j._evaluation.level)}</small></div>`).join('')||'<span class="muted">暂无</span>'}</div>`}).join('')}</div>${dataNotes()}`}
function bars(rows,max){const m=max||Math.max(1,...rows.map(x=>x[1]));return rows.map(([n,v])=>`<div class="bar"><span>${esc(n)}</span><div class="barbg"><div class="barfill" style="width:${Math.min(100,v/m*100)}%"></div></div><b>${v}</b></div>`).join('')}
function statsPage(){const all=evaluated(),normal=normalJobs();const byDir=Object.entries(normal.reduce((m,j)=>(m[j._evaluation.direction]=(m[j._evaluation.direction]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]).slice(0,8),byCity=Object.entries(normal.reduce((m,j)=>(m[j.city]=(m[j.city]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]).slice(0,8);return`<section class="hero"><div><h1>统计分析</h1><div class="subtitle">把候选人适配、数据质量和来源可信度分开看。</div></div>${updateBox()}</section><div class="charts"><div class="card chart"><h3>推荐等级</h3>${bars(['S++','S','A','B','C','D'].map(x=>[x,normal.filter(j=>j._evaluation.level===x).length]))}</div><div class="card chart"><h3>数据质量</h3>${bars(['VALID','PARTIAL'].map(x=>[x,normal.filter(j=>j._evaluation.dataQuality.status===x).length]))}</div><div class="card chart"><h3>方向分布</h3>${bars(byDir)}</div><div class="card chart"><h3>来源</h3>${bars([['官方',normal.filter(j=>j.sourceType==='official').length],['二手',normal.filter(j=>j.sourceType!=='official').length]])}</div></div>${dataNotes()}`}
function offerScore(o){return Math.round((Number(o.fit||0)*.3+Number(o.growth||0)*.25+Number(o.pay||0)*.2+Number(o.city||0)*.15+Number(o.pace||0)*.1)*10)/10}
function offersPage(){return`<section class="hero"><div><h1>Offer 对比</h1><div class="subtitle">匹配30% · 成长25% · 薪酬20% · 城市15% · 工作节奏10%</div></div></section><div class="offers"><form id="offer-form" class="card offer"><div class="grid"><input class="wide" name="company" required placeholder="公司"><input class="wide" name="title" required placeholder="岗位"><input name="location" placeholder="城市"><input name="salary" placeholder="薪资/总包"><div><label>岗位匹配 1–10</label><input name="fit" type="number" min="1" max="10" value="7"></div><div><label>成长空间 1–10</label><input name="growth" type="number" min="1" max="10" value="7"></div><div><label>薪酬福利 1–10</label><input name="pay" type="number" min="1" max="10" value="7"></div><div><label>城市偏好 1–10</label><input name="city" type="number" min="1" max="10" value="7"></div><div><label>工作节奏 1–10</label><input name="pace" type="number" min="1" max="10" value="7"></div><textarea class="wide" name="note" placeholder="备注"></textarea><button class="btn primary wide">加入对比</button></div></form><div class="card offer table"><table><thead><tr><th>公司 / 岗位</th><th>城市</th><th>薪资</th><th>综合</th><th>备注</th><th></th></tr></thead><tbody>${S.offers.length?[...S.offers].sort((a,b)=>offerScore(b)-offerScore(a)).map(o=>`<tr><td><b>${esc(o.company)}</b><br>${esc(o.title)}</td><td>${esc(o.location||'-')}</td><td>${esc(o.salary||'-')}</td><td><b>${offerScore(o)}</b></td><td>${esc(o.note||'-')}</td><td><button class="btn danger" data-delete-offer="${o.id}">删除</button></td></tr>`).join(''):'<tr><td colspan="6" class="muted">暂无 Offer 对比记录</td></tr>'}</tbody></table></div></div>`}
function modal(){if(!S.selected)return'';const j=evaluated().find(x=>x.id===S.selected);if(!j)return'';const v=j._evaluation,p=v.fit.parts,r=v.reasoning;return`<div class="modalbg" data-close="1"><div class="modal" onclick="event.stopPropagation()"><button class="close" data-close="1">×</button><div class="company">${esc(j.company)}</div><h2>${esc(j.title)}</h2><p><span class="pill ${levelClass(v.level)}">${esc(v.level)}</span> ${v.gate.passed&&v.dataQuality.status!=='INVALID'?`<b>适配 ${v.fit.score}/100</b> · 风险 -${v.risk.deduction} · 优先 ${v.priorityScore}`:''}</p><div class="detailgrid"><div class="detailbox"><b>职责 ${p.responsibility}/30</b><span class="muted">${esc(r.responsibility)}</span></div><div class="detailbox"><b>专业语言 ${p.majorLanguage}/20</b><span class="muted">${esc(r.major)}</span></div><div class="detailbox"><b>真实经历 ${p.experience}/25</b><span class="muted">${esc(r.experience)}</span></div><div class="detailbox"><b>方向价值 ${p.careerValue}/15</b><span class="muted">${esc(r.career)}</span></div><div class="detailbox"><b>可补足能力 ${p.learnability}/10</b><span class="muted">${esc(r.learnability)}</span></div><div class="detailbox"><b>信息可信度 ${v.dataQuality.score}/10</b><span class="muted">${esc(v.dataQuality.status)}</span></div></div><h3>Gate / 风险</h3><div class="tags">${v.gate.reasons.map(x=>`<span class="tag bad">× ${esc(x)}</span>`).join('')}${v.risk.items.map(x=>`<span class="tag warn">${esc(x.label)} -${x.value}</span>`).join('')}${v.gate.passed&&!v.risk.items.length?'<span class="tag ok">硬条件通过 · 无明显风险</span>':''}</div><h3>证据化理由</h3><div class="detailbox"><div>${esc(r.experience)}</div><div class="muted" style="margin-top:6px">${esc(r.dataQuality)}</div></div>${j.sourceUrl?`<p><a class="btn primary" target="_blank" rel="noopener" href="${esc(j.sourceUrl)}">${j.sourceType==='official'?'打开官方职位':'查看来源并回官网核验'}</a></p>`:''}</div></div>`}
function render(){const body=S.tab==='jobs'?jobsPage():S.tab==='pipeline'?pipelinePage():S.tab==='stats'?statsPage():offersPage();app.innerHTML=shell(body)}
function parseModule(raw){const a=raw.indexOf('export const liveJobs ='),s=raw.indexOf('[',a),m=raw.indexOf('export const discoveryMeta',s),segment=raw.slice(s,m),end=segment.lastIndexOf('];');if(a<0||s<0||m<0||end<0)throw Error('岗位池格式异常');const jobs=JSON.parse(segment.slice(0,end+1));let meta={};const ms=raw.indexOf('{',m),me=raw.lastIndexOf('};');if(ms>0&&me>ms)try{meta=JSON.parse(raw.slice(ms,me+1))}catch{}return{jobs,meta}}
async function load(){for(const url of DATA_URLS){try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),9000),res=await fetch(url,{cache:'no-store',signal:c.signal});clearTimeout(timer);if(!res.ok)throw Error(String(res.status));const {jobs,meta}=parseModule(await res.text());if(!jobs.length)throw Error('empty');S.jobs=jobs;S.meta=meta;S.updated=meta.updatedAt||jobs[0]?.discoveredAt||'';S.mode='live';render();return}catch(err){console.warn('[board data]',err)}}S.jobs=fb;S.mode='fallback';render()}
function download(name,text,type='application/json'){const a=document.createElement('a'),blob=new Blob([text],{type});a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
app.addEventListener('click',ev=>{const tab=ev.target.closest('[data-tab]')?.dataset.tab;if(tab){S.tab=tab;S.selected=null;render();return}const detail=ev.target.closest('[data-detail]')?.dataset.detail;if(detail){S.selected=detail;render();return}if(ev.target.closest('[data-close]')){S.selected=null;render();return}if(ev.target.id==='reset'){S.filter={q:'',level:'全部',direction:'全部',city:'全部',source:'全部',quality:'全部'};render();return}if(ev.target.id==='more'){S.limit+=40;render();return}if(ev.target.id==='export-json'){download('campus-job-board-applications.json',JSON.stringify({status:S.status,offers:S.offers,exportedAt:new Date().toISOString()},null,2));return}if(ev.target.id==='export-csv'){const rows=[['岗位ID','公司','岗位','状态','等级','适配度','优先分','信息质量'],...evaluated().filter(j=>S.status[j.id]).map(j=>[j.id,j.company,j.title,S.status[j.id],j._evaluation.level,j._evaluation.fit.score,j._evaluation.priorityScore,j._evaluation.dataQuality.status])];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');download('campus-job-board-applications.csv',csv,'text/csv;charset=utf-8');return}if(ev.target.id==='import-json'){document.getElementById('import-file')?.click();return}const del=ev.target.closest('[data-delete-offer]')?.dataset.deleteOffer;if(del){S.offers=S.offers.filter(o=>o.id!==del);save();render()}});
app.addEventListener('input',ev=>{if(ev.target.id==='q'){S.filter.q=ev.target.value;const pos=ev.target.selectionStart;render();const q=document.getElementById('q');q?.focus();q?.setSelectionRange(pos,pos)}});
app.addEventListener('change',ev=>{if(['level','direction','city','source','quality'].includes(ev.target.id)){S.filter[ev.target.id]=ev.target.value;render();return}const id=ev.target.dataset.status;if(id!==undefined){if(ev.target.value)S.status[id]=ev.target.value;else delete S.status[id];save();render();return}if(ev.target.id==='import-file'&&ev.target.files?.[0]){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);S.status=data.status||{};S.offers=data.offers||[];save();render()}catch{alert('JSON 文件格式不正确')}};reader.readAsText(ev.target.files[0])}});
app.addEventListener('submit',ev=>{if(ev.target.id!=='offer-form')return;ev.preventDefault();const data=Object.fromEntries(new FormData(ev.target).entries());S.offers.push({id:'offer-'+Date.now(),...data});save();render()});
render();load();
})();
