(()=>{'use strict';
const LIVE_URLS=['https://raw.githubusercontent.com/lizhenhai2024-alt/AI_Job/main/src/data/live-jobs.js','https://cdn.jsdelivr.net/gh/lizhenhai2024-alt/AI_Job@main/src/data/live-jobs.js'];
const RISK_SOURCES=[
 {exportName:'companyRiskHistory',urls:['https://raw.githubusercontent.com/lizhenhai2024-alt/AI_Job/main/src/data/company-risk-history.js','https://cdn.jsdelivr.net/gh/lizhenhai2024-alt/AI_Job@main/src/data/company-risk-history.js']},
 {exportName:'priorityCompanyRiskHistory',urls:['https://raw.githubusercontent.com/lizhenhai2024-alt/AI_Job/main/src/data/company-risk-history-priority.js','https://cdn.jsdelivr.net/gh/lizhenhai2024-alt/AI_Job@main/src/data/company-risk-history-priority.js']}
];
const RISK_SOURCE_GUIDE=[
 {level:'A',name:'一手材料',sources:'公司公告/官网、交易所/监管、法院/裁判文书、公司官方公众号/微博',usage:'可直接确认事件主体、时间与事实边界。'},
 {level:'B',name:'高可信媒体 / 公司回应',sources:'Reuters、第一财经、界面、澎湃等，或媒体明确引用公司回应',usage:'用于确认公开事件；不把报道范围扩大到未提及的团队、地区或年份。'},
 {level:'C',name:'社区经验线索',sources:'CampusShame、牛客、脉脉、知乎、V2EX 等',usage:'用于发现校招毁约、实习留用、工作强度等线索；保留原帖/快照，不能由单帖外推成全公司事实。'},
 {level:'D',name:'未经核实传闻',sources:'无法追溯原帖、仅截图转述或单一匿名爆料',usage:'默认隐藏，不作为事实、黑名单或投递结论。'}
];
let jobs=[],riskProfiles=[],ready=false,scheduled=false;
const jobById=new Map();

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function companyKey(v=''){return String(v).replace(/[（(].*?[）)]/g,'').replace(/股份有限公司|集团有限公司|有限公司|集团|控股|中国/gi,'').replace(/[\s·,.，、_-]/g,'').toLowerCase();}
function sameCompany(a,b){const x=companyKey(a),y=companyKey(b);return Boolean(x&&y&&(x===y||x.includes(y)||y.includes(x)));}
function parseJobs(raw){const a=raw.indexOf('export const liveJobs ='),s=raw.indexOf('[',a),m=raw.indexOf('export const discoveryMeta',s),segment=raw.slice(s,m),end=segment.lastIndexOf('];');if(a<0||s<0||m<0||end<0)throw Error('岗位池格式异常');return JSON.parse(segment.slice(0,end+1));}
async function fetchText(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),9000);try{const res=await fetch(url,{cache:'no-store',signal:c.signal});if(!res.ok)throw Error(String(res.status));return await res.text();}finally{clearTimeout(timer)}}
async function loadJobs(){for(const url of LIVE_URLS){try{return parseJobs(await fetchText(url))}catch(e){console.warn('[intelligence jobs]',e)}}return[]}
async function loadRiskSet(source){for(const url of source.urls){let blobUrl='';try{const raw=await fetchText(url);blobUrl=URL.createObjectURL(new Blob([raw],{type:'text/javascript'}));const mod=await import(blobUrl);const rows=mod[source.exportName];return Array.isArray(rows)?rows:[]}catch(e){console.warn(`[intelligence risk ${source.exportName}]`,e)}finally{if(blobUrl)URL.revokeObjectURL(blobUrl)}}return[]}
async function loadRisk(){const groups=await Promise.all(RISK_SOURCES.map(loadRiskSet));return groups.flat()}
function riskFor(company){return riskProfiles.find(p=>sameCompany(p.company,company)||(p.aliases||[]).some(a=>sameCompany(a,company)))||null}
function typeLabel(type){return({layoff:'裁员/优化',restructuring:'组织重组/人员调整',intern_conversion:'实习转正/留用风险',offer_change:'校招毁约/缩招',work_intensity:'长期加班/工作强度争议',compensation:'薪资倒挂/调薪争议'})[type]||'历史事件'}
function levelLabel(level){return({A:'一手材料',B:'高可信媒体/公司回应',C:'社区经验线索',D:'未经核实传闻'})[level]||'证据待核'}
function confidenceLabel(comp={}){return comp.confidence==='high'?'高可信·企业官方披露':comp.confidence==='medium'?'中可信·二手来源待官网复核':'未披露';}
function validRiskEvent(e){return Boolean(e&&e.id&&e.type&&/^\d{4}-\d{2}-\d{2}$/.test(String(e.date||''))&&e.source&&/^https?:\/\//i.test(String(e.sourceUrl||''))&&['A','B','C','D'].includes(String(e.evidenceLevel||'')));}
function jobForCard(card){const id=card.querySelector('[data-detail]')?.dataset.detail;return jobById.get(String(id||''))||null}
function salaryText(job){const m=job?.monthlySalary||job?.compensation?.monthlyDisplay||'',a=job?.annualSalary||job?.compensation?.annualDisplay||'';if(!job?.compensation?.disclosed)return'';return [m,a].filter(Boolean).join(' · ')}
function create(tag,cls='',text=''){const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n}
function sourceLink(event){if(!/^https?:\/\//i.test(String(event?.sourceUrl||'')))return null;const a=create('a','intel-link','证据');a.href=event.sourceUrl;a.target='_blank';a.rel='noopener';return a}
function riskEvents(profile){return(profile?.events||[]).filter(validRiskEvent).filter(e=>e.evidenceLevel!=='D').sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))}
function riskSourceGuideNode(){const details=create('details','intel-risk-source-guide');details.append(create('summary','intel-risk-source-summary','来源说明：A/B 高可信 · CampusShame / 牛客 / 脉脉等为社区线索'));const body=create('div','intel-risk-source-body');for(const item of RISK_SOURCE_GUIDE){const row=create('div','intel-risk-source-row');row.append(create('b','',`${item.level}级 · ${item.name}`),create('div','muted',`典型来源：${item.sources}`),create('div','muted',`使用原则：${item.usage}`));body.append(row)}body.append(create('p','intel-risk-source-foot','CampusShame 是校招案例汇总/证据索引，主要引用牛客、脉脉、知乎等公开论坛，因此默认按 C 级二手社区线索处理；若条目可回溯到 A/B 级原始证据，则以原始证据等级为准。'));details.append(body);return details}

function decorateCard(card){if(card.dataset.intelV13==='1')return;const job=jobForCard(card);if(!job)return;const tags=card.querySelector('.tags');if(!tags)return;
 const salary=salaryText(job),comp=job.compensation||{};if(salary){const t=create('span','tag ok',`💰 ${salary}`);t.title=`薪资来源：${comp.sourceLabel||'岗位来源'}；可信度：${confidenceLabel(comp)}`;tags.append(t);tags.append(create('span',comp.confidence==='high'?'tag ok':'tag warn',comp.confidence==='high'?'薪资·高可信':'薪资·待官网复核'))}
 const events=riskEvents(riskFor(job.company));if(events.length){const high=events.filter(e=>['A','B'].includes(e.evidenceLevel)&&e.sentiment==='negative').length,intern=events.filter(e=>e.type==='intern_conversion').length;if(high)tags.append(create('span','tag warn',`历史风险 A/B·${high}`));if(intern)tags.append(create('span','tag',`实习留用线索 ${intern}`));}
 card.dataset.intelV13='1';}

function modalJob(modal){const company=modal.querySelector('.company')?.textContent?.trim()||'',title=modal.querySelector('h2')?.textContent?.trim()||'';return jobs.find(j=>sameCompany(j.company,company)&&String(j.title||'').trim()===title)||null}
function detailBox(label,value){const box=create('div','detailbox');const b=create('b','',label),span=create('span','muted',value||'未披露');box.append(b,span);return box}
function decorateModal(modal){if(modal.dataset.intelV13==='1')return;const job=modalJob(modal);if(!job)return;const anchor=modal.querySelector('h3');const salarySection=create('div','intel-section');salarySection.append(create('h3','','薪资情报'));const grid=create('div','detailgrid');const comp=job.compensation||{};grid.append(detailBox('月薪',job.monthlySalary||comp.monthlyDisplay||'未披露'),detailBox('年薪',job.annualSalary||comp.annualDisplay||'未披露'),detailBox('原始薪资',comp.raw||job.salary||'未披露'),detailBox('薪资来源',comp.sourceLabel||'岗位来源未披露'),detailBox('薪资可信度',confidenceLabel(comp)),detailBox('薪资证据',comp.evidence||'来源未披露数字薪资'));salarySection.append(grid);salarySection.append(create('p','intel-note','月薪/年薪只使用来源页或JD明确披露数字；未写薪数时仅按12薪估算，并显式标记。不擅自加入年终奖、股票、补贴或绩效奖金。'));
 const riskSection=create('div','intel-section');riskSection.append(create('h3','','公司往年风险事件 / 实习留用线索'),riskSourceGuideNode());const events=riskEvents(riskFor(job.company));if(!events.length){riskSection.append(create('div','detailbox muted','暂无满足“时间 + 来源 + 可追溯链接 + 证据等级”要求的已录入事件；这不等于“无风险”，仍需核验具体团队和年份。'))}else{for(const event of events.slice(0,5)){const row=create('div','detailbox intel-event');const head=create('div','intel-event-head');head.append(create('b','',`${event.date||'日期待核'} · ${typeLabel(event.type)}`),create('span',`tag ${['A','B'].includes(event.evidenceLevel)?'warn':''}`,`${event.evidenceLevel}级 · ${levelLabel(event.evidenceLevel)}`));row.append(head,create('div','intel-event-title',event.title||'历史事件'));if(event.summary)row.append(create('div','muted intel-event-summary',event.summary));const foot=create('div','muted intel-event-foot',`范围：${event.scope||'待核'} · 来源：${event.source||'待核'}`);const link=sourceLink(event);if(link){foot.append(document.createTextNode(' · '),link)}row.append(foot);riskSection.append(row)}}
 riskSection.append(create('p','intel-note','历史事件不等于当前状态；A/B级可作为高可信风险情报，C级社区经验只用于面试反问/核验，D级传闻默认隐藏。公司历史风险不参与本看板 S/A/B 或 Candidate Fit 计算。'));
 if(anchor){anchor.insertAdjacentElement('beforebegin',riskSection);riskSection.insertAdjacentElement('beforebegin',salarySection)}else{modal.append(salarySection,riskSection)}modal.dataset.intelV13='1';}

function decorateHelp(){document.querySelectorAll('.card.help ul').forEach(ul=>{if(ul.querySelector('[data-v13-note]'))return;const li=document.createElement('li');li.dataset.v13Note='1';li.innerHTML='<b>V1.3 情报层</b>：岗位层展示月薪/年薪、来源与可信度；公司风险按 A 一手材料、B 高可信媒体、C 社区线索、D 未核实传闻分级。CampusShame、牛客、脉脉等社区内容默认只作核验线索，不参与 S/A/B，也不把匿名单帖当事实。';ul.append(li)})}
function installStyle(){if(document.getElementById('intel-v13-style'))return;const s=document.createElement('style');s.id='intel-v13-style';s.textContent='.intel-section{margin-top:14px}.intel-note{font-size:12px;color:var(--muted);margin:6px 0 10px}.intel-event{margin:7px 0}.intel-event-head{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.intel-event-title{font-weight:700;margin-top:5px}.intel-event-summary{margin-top:4px;line-height:1.55}.intel-event-foot{font-size:12px;margin-top:5px}.intel-link{color:var(--blue);text-decoration:none}.intel-link:hover{text-decoration:underline}.intel-risk-source-guide{margin:8px 0 10px;border:1px solid var(--line);border-radius:10px;background:#fafbfe}.intel-risk-source-guide summary{cursor:pointer;list-style:none;padding:8px 10px;font-size:12px;font-weight:700;color:#5f6b80}.intel-risk-source-guide summary::-webkit-details-marker{display:none}.intel-risk-source-guide summary:before{content:"＋";display:inline-block;width:18px;color:#7b879a}.intel-risk-source-guide[open] summary:before{content:"－"}.intel-risk-source-body{padding:0 9px 9px;display:grid;gap:7px}.intel-risk-source-row{background:#fff;border:1px solid var(--line);border-radius:8px;padding:7px 9px}.intel-risk-source-row b{display:block;font-size:12px;color:#344054;margin-bottom:2px}.intel-risk-source-row .muted{font-size:12px;line-height:1.5}.intel-risk-source-foot{font-size:12px;line-height:1.55;color:var(--muted);margin:2px 1px 0}';document.head.append(s)}
function decorate(){if(!ready)return;installStyle();document.querySelectorAll('.card.job').forEach(decorateCard);const modal=document.querySelector('.modal');if(modal)decorateModal(modal);decorateHelp()}
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;decorate()})}
async function init(){const [j,r]=await Promise.all([loadJobs(),loadRisk()]);jobs=j;riskProfiles=r;jobById.clear();for(const job of jobs)jobById.set(String(job.id),job);ready=true;decorate()}
const root=document.getElementById('app');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});init();
})();
