/* 2027届投递清单（收窄版）
 * 由 docs/投递清单_2027届_收窄版.md 同步。V1.2 scoring.js 不读这份数据。
 * 待归类按长期发展前景标 避开 / 再看，不计入冲刺/主力/保底。
 */
window.SHORTLIST_META = {
  generatedAt: '2026-09-11',
  poolSize: 1698,
  apply: 67,
  pending: 13,
};
window.SHORTLIST_BUCKETS = {
  sprint: { label: '冲刺', how: '必须逐份定制。每份针对 JD 改 3–5 处关键词，附上「中车海外 → 安斯泰莫 → 把技术语言翻译成客户语言」。' },
  core: { label: '主力', how: '模板+微调。按「海外市场 / 跨境运营 / 国际供应链」三类各做一版简历。' },
  safety: { label: '保底', how: '直接投。用来保证手上有 offer，不投入定制时间。' },
  pending: { label: '待归类', how: '公司不在行业白名单。按长期前景：教培 / 游戏 / 国内互联网先别投；货拉拉、极兔驻外再判断。' },
};
window.SHORTLIST_ITEMS = [
  {
    "id": "s-万兴科技-产品gtm专员",
    "bucket": "sprint",
    "company": "万兴科技",
    "companyId": "wondershare",
    "title": "产品GTM专员",
    "city": "长沙",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://wondersharecampus.zhiye.com/campus/detail?jobAdId=93cec780-3c95-4e9f-9c99-4328762ee1ac",
    "prospect": "apply"
  },
  {
    "id": "s-拓竹科技-海外市场营销-产品营销方向",
    "bucket": "sprint",
    "company": "拓竹科技",
    "companyId": "bambu",
    "title": "海外市场营销 - 产品营销方向",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://bambulab.jobs.feishu.cn/campus/m/position/7670524540493777193/detail",
    "prospect": "apply"
  },
  {
    "id": "s-小鹏汽车-27届校招海外产品营销培训生-中东非",
    "bucket": "sprint",
    "company": "小鹏汽车",
    "companyId": "xpeng",
    "title": "【27届校招】海外产品营销培训生-中东非",
    "city": "广州",
    "track": "汽车/新能源出海",
    "channel": "管培生",
    "url": "https://xiaopeng.jobs.feishu.cn/campus/m/position/7658239611093879066/detail",
    "prospect": "apply"
  },
  {
    "id": "s-拓竹科技-gtm",
    "bucket": "sprint",
    "company": "拓竹科技",
    "companyId": "bambu",
    "title": "GTM",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://bambulab.jobs.feishu.cn/campus/m/position/7670145644522129710/detail",
    "prospect": "apply"
  },
  {
    "id": "s-传音控股-海东青计划-gtmgo-to-market方向j20132",
    "bucket": "sprint",
    "company": "传音控股",
    "companyId": "transsion",
    "title": "海东青计划·GTM（Go-to-Market）方向(J20132)",
    "city": "全国",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://transsion.zhiye.com/campus/detail?jobAdId=270965302",
    "note": "长期外派（东南亚/拉美/非洲）",
    "prospect": "apply"
  },
  {
    "id": "s-图拉斯-海外运营管培生-魔方",
    "bucket": "sprint",
    "company": "图拉斯",
    "companyId": "torras",
    "title": "海外运营管培生—魔方",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://lanhevip.jobs.feishu.cn/605335/position/7682767011525003583/detail",
    "prospect": "apply"
  },
  {
    "id": "s-拓竹科技-海外市场社媒培训生-欧美市场",
    "bucket": "sprint",
    "company": "拓竹科技",
    "companyId": "bambu",
    "title": "海外市场社媒培训生 - 欧美市场",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://bambulab.jobs.feishu.cn/campus/m/position/7670527057306339630/detail",
    "prospect": "apply"
  },
  {
    "id": "s-创维集团-海外营销管培生",
    "bucket": "sprint",
    "company": "创维集团",
    "companyId": "skyworth",
    "title": "海外营销管培生",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://skyworth.hotjob.cn/SU668e3a541eb8050602c1b176/pb/posDetail.html?postId=6a69d1db53b4650cd34cda07&postType=campus",
    "prospect": "apply"
  },
  {
    "id": "s-三一集团-海外销服管培生-黄埔计划",
    "bucket": "sprint",
    "company": "三一集团",
    "companyId": "sany",
    "title": "海外销服管培生——黄埔计划",
    "city": "广州",
    "track": "汽车/新能源出海",
    "channel": "管培生",
    "url": "https://sany.zhiye.com/campus/detail?jobAdId=270972186",
    "note": "长期外派（全球海外市场，轮岗后派驻）",
    "prospect": "apply"
  },
  {
    "id": "s-海信-海外产品营销j44569",
    "bucket": "sprint",
    "company": "海信",
    "companyId": "hisense",
    "title": "海外产品营销(J44569)",
    "city": "青岛/佛山",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://jobs.hisense.com/campus/detail?jobAdId=350355037",
    "prospect": "apply"
  },
  {
    "id": "s-致欧家居-外贸管培生27届校招",
    "bucket": "sprint",
    "company": "致欧家居",
    "title": "外贸管培生（27届校招）",
    "city": "郑州",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://songmicshome.jobs.feishu.cn/852372/m/position/7672664313010604351/detail",
    "prospect": "apply"
  },
  {
    "id": "s-致欧家居-tiktok运营管培生27届校招",
    "bucket": "sprint",
    "company": "致欧家居",
    "title": "TikTok运营管培生（27届校招）",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://songmicshome.jobs.feishu.cn/852372/m/position/7672651691866802459/detail",
    "prospect": "apply"
  },
  {
    "id": "s-图拉斯-亚马逊运营管培生-英语方向",
    "bucket": "sprint",
    "company": "图拉斯",
    "companyId": "torras",
    "title": "亚马逊运营管培生-英语方向",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://lanhevip.jobs.feishu.cn/605335/position/7682769421529516329/detail",
    "prospect": "apply"
  },
  {
    "id": "s-小鹏汽车-27届校招海外售后策略培训生售后运营-数据分析",
    "bucket": "sprint",
    "company": "小鹏汽车",
    "companyId": "xpeng",
    "title": "【27届校招】海外售后策略培训生（售后运营/数据分析）",
    "city": "广州",
    "track": "汽车/新能源出海",
    "channel": "管培生",
    "url": "https://xiaopeng.jobs.feishu.cn/campus/m/position/7672610350872906034/detail",
    "prospect": "apply"
  },
  {
    "id": "s-babycare-2027校招-跨境电商运营管培生",
    "bucket": "sprint",
    "company": "Babycare",
    "title": "2027校招-跨境电商运营管培生",
    "city": "杭州",
    "track": "品牌方跨境",
    "channel": "管培生",
    "url": "https://babycare.zhiye.com/campus/detail?jobAdId=390849526",
    "prospect": "apply"
  },
    {
    "id": "s-图拉斯-内容管培生",
    "bucket": "sprint",
    "company": "图拉斯",
    "companyId": "torras",
    "title": "内容管培生",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://lanhevip.jobs.feishu.cn/605335/position/7682767011524921663/detail",
    "prospect": "apply"
      },
  {
    "id": "s-创维集团-海外电商管培生",
    "bucket": "sprint",
    "company": "创维集团",
    "companyId": "skyworth",
    "title": "海外电商管培生",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://skyworth.hotjob.cn/SU668e3a541eb8050602c1b176/pb/posDetail.html?postId=6a69d1dde05c792b8ed1e35e&postType=campus",
    "note": "长期海外外派+海外出差",
    "prospect": "apply"
  },
  {
    "id": "s-傲基科技-27校招-管培生独立站方向",
    "bucket": "sprint",
    "company": "傲基科技",
    "title": "27校招-管培生（独立站方向）",
    "city": "深圳",
    "track": "品牌方跨境",
    "channel": "管培生",
    "url": "https://aukeys.zhiye.com/campus/detail?jobAdId=085628db-9d5d-4c93-a30e-26302a9daad7",
    "prospect": "apply"
  },
  {
    "id": "s-oppo-产品营销经理海外-小语种",
    "bucket": "sprint",
    "company": "OPPO",
    "companyId": "oppo",
    "title": "产品营销经理（海外-小语种）",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://careers.oppo.com/university/oppo/campus/post/1816",
    "prospect": "apply"
  },
  {
    "id": "c-杭州宇树科技股份有限公司-市场策划与宣传海外",
    "bucket": "core",
    "company": "杭州宇树科技股份有限公司",
    "companyId": "unitree",
    "title": "市场策划与宣传（海外）",
    "city": "杭州",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://unitree.zhiye.com/campus/detail?jobAdId=511173675",
    "prospect": "apply"
  },
  {
    "id": "c-oppo-媒介经理海外-小语种",
    "bucket": "core",
    "company": "OPPO",
    "companyId": "oppo",
    "title": "媒介经理（海外-小语种）",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://careers.oppo.com/university/oppo/campus/post/1818",
    "prospect": "apply"
  },
  {
    "id": "c-万兴科技-品牌策划专员",
    "bucket": "core",
    "company": "万兴科技",
    "companyId": "wondershare",
    "title": "品牌策划专员",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://wondersharecampus.zhiye.com/campus/detail?jobAdId=621129074",
    "prospect": "apply"
  },
  {
    "id": "c-拓竹科技-物流尾程运营",
    "bucket": "core",
    "company": "拓竹科技",
    "companyId": "bambu",
    "title": "物流尾程运营",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://bambulab.jobs.feishu.cn/campus/m/position/7670528894689102122/detail",
    "prospect": "apply"
  },
  {
    "id": "c-泡泡玛特-全球用户体验运营",
    "bucket": "core",
    "company": "泡泡玛特",
    "title": "全球用户体验运营",
    "city": "北京",
    "track": "品牌方跨境",
    "channel": "—",
    "url": "https://popmart.zhiye.com/campus/detail?jobAdId=230938448",
    "prospect": "apply"
  },
  {
    "id": "c-vivo-品牌经理海外业务-27届秋招",
    "bucket": "core",
    "company": "vivo",
    "companyId": "vivo",
    "title": "品牌经理（海外业务）-27届秋招",
    "city": "东莞",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://hr-campus.vivo.com/campus/detail?jobAdId=eb089def-853b-4ba1-9f49-275e34b228e1",
    "prospect": "apply"
  },
  {
    "id": "c-安克创新-渠道运营经理-深圳",
    "bucket": "core",
    "company": "安克创新",
    "companyId": "anker",
    "title": "渠道运营经理-深圳",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://career.anker.com.cn/larkJobDetail/?websiteId=6962795203808217351&jobId=7676417621721434410",
    "prospect": "apply"
  },
  {
    "id": "c-安克创新-渠道运营经理-长沙",
    "bucket": "core",
    "company": "安克创新",
    "companyId": "anker",
    "title": "渠道运营经理-长沙",
    "city": "长沙",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://career.anker.com.cn/larkJobDetail/?websiteId=6962795203808217351&jobId=7676413687209281830",
    "prospect": "apply"
  },
  {
    "id": "c-国贸股份-海外业务岗j13645",
    "bucket": "core",
    "company": "国贸股份",
    "title": "海外业务岗(J13645)",
    "city": "国外",
    "track": "央国企国际业务",
    "channel": "—",
    "url": "https://itg.zhiye.com/gmkgxzxq?jobId=311179882&key=gmgf&p=1^14,3^24&p1=1^14&p2=3^24&job=campus",
    "note": "长期海外工作地点",
    "prospect": "apply"
  },
  {
    "id": "c-三一集团-国际运营管理专员",
    "bucket": "core",
    "company": "三一集团",
    "companyId": "sany",
    "title": "国际运营管理专员",
    "city": "广州",
    "track": "汽车/新能源出海",
    "channel": "—",
    "url": "https://sany.zhiye.com/campus/detail?jobAdId=270976078",
    "prospect": "apply"
  },
  {
    "id": "c-泡泡玛特-跨境电商运营美洲区",
    "bucket": "core",
    "company": "泡泡玛特",
    "title": "跨境电商运营（美洲区）",
    "city": "上海",
    "track": "品牌方跨境",
    "channel": "—",
    "url": "https://popmart.zhiye.com/campus/detail?jobAdId=230940454",
    "prospect": "apply"
  },
  {
    "id": "c-傲基科技-27校招-平台运营岗",
    "bucket": "core",
    "company": "傲基科技",
    "title": "27校招-平台运营岗",
    "city": "深圳",
    "track": "品牌方跨境",
    "channel": "—",
    "url": "https://aukeys.zhiye.com/campus/detail?jobAdId=230936288",
    "prospect": "apply"
  },
  {
    "id": "c-傲基科技-27校招-独立站运营专员",
    "bucket": "core",
    "company": "傲基科技",
    "title": "27校招-独立站运营专员",
    "city": "深圳",
    "track": "品牌方跨境",
    "channel": "—",
    "url": "https://aukeys.zhiye.com/campus/detail?jobAdId=230936303",
    "prospect": "apply"
  },
  {
    "id": "c-正浩创新ecoflow-电商销售英语",
    "bucket": "core",
    "company": "正浩创新EcoFlow",
    "companyId": "ecoflow",
    "title": "电商销售（英语）",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://jobs.ecoflow.com/602892/position/7678715348036700426/detail",
    "prospect": "apply"
  },
  {
    "id": "c-小米-海外商业化运营",
    "bucket": "core",
    "company": "小米",
    "companyId": "xiaomi",
    "title": "海外商业化运营",
    "city": "北京",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://xiaomi.jobs.f.mioffice.cn/campus/m/position/7671293278901668132/detail",
    "note": "关键技能需补足",
    "prospect": "apply"
  },
  {
    "id": "c-扬腾创新-全球市场营销",
    "bucket": "core",
    "company": "扬腾创新",
    "title": "全球市场营销",
    "city": "福建省·福州市",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://yangtenginnovation-compus.zhiye.com/campus/detail?jobAdId=511198630",
    "note": "关键技能需补足",
    "prospect": "apply"
  },
  {
    "id": "c-小米-gtm运营专员-外派",
    "bucket": "core",
    "company": "小米",
    "companyId": "xiaomi",
    "title": "GTM运营专员-外派",
    "city": "约翰内斯堡、开罗",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://xiaomi.jobs.f.mioffice.cn/campus/m/position/7670935284204374335/detail",
    "prospect": "apply"
  },
  {
    "id": "c-小米-gtm-operations-specialist-local",
    "bucket": "core",
    "company": "小米",
    "companyId": "xiaomi",
    "title": "GTM Operations Specialist-local",
    "city": "布拉格直辖市、雅加达",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://xiaomi.jobs.f.mioffice.cn/campus/m/position/7670932811557177642/detail",
    "prospect": "apply"
  },
  {
    "id": "c-小米-gtm计划专员",
    "bucket": "core",
    "company": "小米",
    "companyId": "xiaomi",
    "title": "GTM计划专员",
    "city": "北京",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://xiaomi.jobs.f.mioffice.cn/campus/m/position/7670886003045288228/detail",
    "prospect": "apply"
  },
  {
    "id": "c-海信-海外电商运营j44567",
    "bucket": "core",
    "company": "海信",
    "companyId": "hisense",
    "title": "海外电商运营(J44567)",
    "city": "山东省·青岛市",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://jobs.hisense.com/campus/detail?jobAdId=350355039",
    "prospect": "apply"
  },
  {
    "id": "c-小鹏汽车-27届校招海外技术培训运营培训生",
    "bucket": "core",
    "company": "小鹏汽车",
    "companyId": "xpeng",
    "title": "【27届校招】海外技术培训运营培训生",
    "city": "广州",
    "track": "汽车/新能源出海",
    "channel": "管培生",
    "url": "https://xiaopeng.jobs.feishu.cn/campus/m/position/7680779487646763315/detail",
    "prospect": "apply"
  },
  {
    "id": "c-vivo-产品营销经理海外业务-27届秋招",
    "bucket": "core",
    "company": "vivo",
    "companyId": "vivo",
    "title": "产品营销经理（海外业务）-27届秋招",
    "city": "东莞",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://hr-campus.vivo.com/campus/detail?jobAdId=561282543",
    "prospect": "apply"
  },
  {
    "id": "c-小鹏汽车-27届校招海外市场分析培训生",
    "bucket": "core",
    "company": "小鹏汽车",
    "companyId": "xpeng",
    "title": "【27届校招】海外市场分析培训生",
    "city": "广州",
    "track": "汽车/新能源出海",
    "channel": "管培生",
    "url": "https://xiaopeng.jobs.feishu.cn/campus/m/position/7675298796682692900/detail",
    "prospect": "apply"
  },
  {
    "id": "c-扬腾创新-跨境电商运营校招生亚马逊j13038",
    "bucket": "core",
    "company": "扬腾创新",
    "title": "跨境电商运营校招生（亚马逊）(J13038)",
    "city": "福建省·福州市",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://yangtenginnovation-compus.zhiye.com/campus/detail?jobAdId=511199414",
    "note": "关键技能需补足",
    "prospect": "apply"
  },
  {
    "id": "c-万兴科技-geo运营专员",
    "bucket": "core",
    "company": "万兴科技",
    "companyId": "wondershare",
    "title": "GEO运营专员",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://wondersharecampus.zhiye.com/campus/detail?jobAdId=621129070",
    "prospect": "apply"
  },
  {
    "id": "c-安克创新-品牌传播专员-深圳",
    "bucket": "core",
    "company": "安克创新",
    "companyId": "anker",
    "title": "品牌传播专员-深圳",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://career.anker.com.cn/larkJobDetail/?websiteId=6962795203808217351&jobId=7676436233111619849",
    "prospect": "apply"
  },
  {
    "id": "c-oppo-市场管理培训生-海外",
    "bucket": "core",
    "company": "OPPO",
    "companyId": "oppo",
    "title": "市场管理培训生-海外",
    "city": "东莞",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://careers.oppo.com/university/oppo/campus/post/1869",
    "prospect": "apply"
  },
  {
    "id": "c-传音控股-ai运营专员重庆j20342",
    "bucket": "core",
    "company": "传音控股",
    "companyId": "transsion",
    "title": "AI运营专员（重庆）(J20342)",
    "city": "重庆",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://transsion.zhiye.com/campus/detail?jobAdId=270968817",
    "prospect": "apply"
  },
  {
    "id": "c-致欧家居-国际运输管培生27届校招",
    "bucket": "core",
    "company": "致欧家居",
    "title": "国际运输管培生（27届校招）",
    "city": "郑州",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://songmicshome.jobs.feishu.cn/852372/m/position/7672663294267885860/detail",
    "note": "关键技能需补足",
    "prospect": "apply"
  },
  {
    "id": "c-致欧家居-跨境电商运营管培生27届校招",
    "bucket": "core",
    "company": "致欧家居",
    "title": "跨境电商运营管培生（27届校招）",
    "city": "郑州",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://songmicshome.jobs.feishu.cn/852372/m/position/7672665123584903460/detail",
    "prospect": "apply"
  },
  {
    "id": "c-名创优品-海外运营创优生英语j17243",
    "bucket": "core",
    "company": "名创优品",
    "title": "海外运营创优生（英语）(J17243)",
    "city": "广州",
    "track": "品牌方跨境",
    "channel": "—",
    "url": "https://miniso.zhiye.com/campus/detail?jobAdId=351611791",
    "prospect": "apply"
  },
  {
    "id": "c-图拉斯-海外商务管培生",
    "bucket": "core",
    "company": "图拉斯",
    "companyId": "torras",
    "title": "海外商务管培生",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://lanhevip.jobs.feishu.cn/605335/position/7680181730569439497/detail",
    "prospect": "apply"
  },
  {
    "id": "c-安克创新-全球服务运营专员-深圳",
    "bucket": "core",
    "company": "安克创新",
    "companyId": "anker",
    "title": "全球服务运营专员-（深圳）",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://career.anker.com.cn/larkJobDetail/?websiteId=6962795203808217351&jobId=7672310259146836265",
    "prospect": "apply"
  },
  {
    "id": "c-英科医疗-英科再生-27届校招国际物流专员",
    "bucket": "core",
    "company": "英科医疗/英科再生",
    "title": "【27届校招】国际物流专员",
    "city": "淄博",
    "track": "品牌方跨境",
    "channel": "—",
    "url": "https://global-intco.jobs.feishu.cn/251907/m/position/7673331641541265715/detail",
    "prospect": "apply"
  },
  {
    "id": "c-泡泡玛特-品牌市场营销美洲区",
    "bucket": "core",
    "company": "泡泡玛特",
    "title": "品牌市场营销（美洲区）",
    "city": "北京",
    "track": "品牌方跨境",
    "channel": "—",
    "url": "https://popmart.zhiye.com/campus/detail?jobAdId=230938452",
    "prospect": "apply"
  },
  {
    "id": "c-传音控股-运营专员j20360",
    "bucket": "core",
    "company": "传音控股",
    "companyId": "transsion",
    "title": "运营专员(J20360)",
    "city": "上海",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://transsion.zhiye.com/campus/detail?jobAdId=270968880",
    "note": "关键技能需补足",
    "prospect": "apply"
  },
  {
    "id": "c-shein-供应链管理管培生广州-国际物流-2027届",
    "bucket": "core",
    "company": "SHEIN",
    "companyId": "shein",
    "title": "供应链管理管培生（广州）-国际物流-2027届",
    "city": "广州",
    "track": "品牌方跨境",
    "channel": "管培生",
    "url": "https://app.mokahr.com/campus-recruitment/shein/2932#/job/bd52e22a-ba4d-424e-986a-66fb981a8a79",
    "prospect": "apply"
  },
  {
    "id": "c-创维集团-海外供应链管培生",
    "bucket": "core",
    "company": "创维集团",
    "companyId": "skyworth",
    "title": "海外供应链管培生",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "管培生",
    "url": "https://skyworth.hotjob.cn/SU668e3a541eb8050602c1b176/pb/posDetail.html?postId=6a69d1dcba2dc64cbb91a332&postType=campus",
    "prospect": "apply"
  },
  {
    "id": "c-扬腾创新-全球供应链管理校招生-j13006",
    "bucket": "core",
    "company": "扬腾创新",
    "title": "全球供应链管理校招生 (J13006)",
    "city": "福建省·福州市",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://yangtenginnovation-compus.zhiye.com/campus/detail?jobAdId=511197097",
    "note": "关键技能需补足",
    "prospect": "apply"
  },
  {
    "id": "c-shein-全球供应链管培生广州-2027届",
    "bucket": "core",
    "company": "SHEIN",
    "companyId": "shein",
    "title": "全球供应链管培生（广州）-2027届",
    "city": "广州",
    "track": "品牌方跨境",
    "channel": "管培生",
    "url": "https://app.mokahr.com/campus-recruitment/shein/2932#/job/b46690dd-38e0-46d8-a813-644fcbd29e2e",
    "prospect": "apply"
  },
  {
    "id": "c-顾家家居-电商运营-跨境方向kj",
    "bucket": "core",
    "company": "顾家家居",
    "title": "电商运营-跨境方向(KJ)",
    "city": "杭州",
    "track": "品牌方跨境",
    "channel": "—",
    "url": "https://app.mokahr.com/campus-recruitment/kuka/172508#/job/43a03aab-3353-403c-8cd7-86ded432e493",
    "prospect": "apply"
  },
  {
    "id": "b-万兴科技-用户运营专员",
    "bucket": "safety",
    "company": "万兴科技",
    "companyId": "wondershare",
    "title": "用户运营专员",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://wondersharecampus.zhiye.com/campus/detail?jobAdId=621129068",
    "prospect": "apply"
  },
  {
    "id": "b-传音控股-独立站运营专员j20321",
    "bucket": "safety",
    "company": "传音控股",
    "companyId": "transsion",
    "title": "独立站运营专员(J20321)",
    "city": "深圳",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://transsion.zhiye.com/campus/detail?jobAdId=270968804",
    "prospect": "apply"
  },
  {
    "id": "b-优衣库-2027迅销集团优衣库umc经营管理培训生j15322",
    "bucket": "safety",
    "company": "优衣库",
    "title": "2027迅销集团优衣库UMC经营管理培训生(J15322)",
    "city": "全国",
    "track": "外企",
    "channel": "管培生",
    "url": "https://uniqlo.zhiye.com/campus/detail?jobAdId=720028483",
    "prospect": "apply"
  },
  {
    "id": "b-shein-国际物流运营专员广州-2027届",
    "bucket": "safety",
    "company": "SHEIN",
    "companyId": "shein",
    "title": "国际物流运营专员（广州）-2027届",
    "city": "广州",
    "track": "品牌方跨境",
    "channel": "—",
    "url": "https://app.mokahr.com/campus-recruitment/shein/2932#/job/9219b306-42af-4ac9-9adc-96d9bda906e6",
    "prospect": "apply"
  },
  {
    "id": "b-赛轮轮胎-全球业务运营支持岗j16044",
    "bucket": "safety",
    "company": "赛轮轮胎",
    "title": "全球业务运营支持岗(J16044)",
    "city": "山东省·青岛市",
    "track": "汽车/新能源出海",
    "channel": "—",
    "url": "https://sailuntire.zhiye.com/campus/detail?jobAdId=190850853",
    "prospect": "apply"
  },
  {
    "id": "b-三一集团-国际物流管理专员",
    "bucket": "safety",
    "company": "三一集团",
    "companyId": "sany",
    "title": "国际物流管理专员",
    "city": "北京",
    "track": "汽车/新能源出海",
    "channel": "—",
    "url": "https://sany.zhiye.com/campus/detail?jobAdId=270971578",
    "prospect": "apply"
  },
  {
    "id": "b-海信-品牌营销海外推广j45043",
    "bucket": "safety",
    "company": "海信",
    "companyId": "hisense",
    "title": "品牌营销（海外推广）(J45043)",
    "city": "山东省·青岛市",
    "track": "智能硬件出海",
    "channel": "—",
    "url": "https://jobs.hisense.com/campus/detail?jobAdId=350355642",
    "prospect": "apply"
  },
  {
    "id": "p-字节跳动-内容产品经理-tiktok-shop",
    "bucket": "pending",
    "company": "字节跳动",
    "companyId": "bytedance",
    "title": "内容产品经理 - TikTok Shop",
    "city": "上海",
    "track": "待归类:互联网与科技",
    "channel": "—",
    "url": "https://jobs.bytedance.com/campus",
    "prospect": "avoid",
    "why": "国内互联网平台。互联网 GTM 拼不过市场营销+大厂实习，三年锁进内容池。"
  },
  {
    "id": "p-阿里巴巴-国际体验运营-小语种",
    "bucket": "pending",
    "company": "阿里巴巴",
    "title": "国际体验运营-小语种",
    "city": "杭州",
    "track": "待归类:互联网与科技",
    "channel": "—",
    "url": "https://campus-talent.alibaba.com/campus/position/detail?id=199907640018",
    "note": "关键技能需补足",
    "prospect": "avoid",
    "why": "国内互联网国际化岗。英专没有专业壁垒，不作为主攻。"
  },
  {
    "id": "p-货拉拉-全球拓展管培生校招",
    "bucket": "pending",
    "company": "货拉拉",
    "title": "全球拓展管培生（校招）",
    "city": "香港",
    "track": "待归类:互联网与科技",
    "channel": "管培生",
    "url": "https://app.mokahr.com/campus-recruitment/huolalahr/98660#/job/0a25484b-c0ce-4a02-8c27-abaab9d42299",
    "prospect": "watch",
    "why": "跨境服务、香港。不在四类白名单，人工判断后再决定。"
  },
  {
    "id": "p-新东方深圳学校-27届校招天津国际-运营管培生j66139",
    "bucket": "pending",
    "company": "新东方深圳学校",
    "title": "【27届校招】天津国际——运营管培生(J66139)",
    "city": "天津",
    "track": "待归类:品牌与新消费",
    "channel": "管培生",
    "url": "https://xdf.zhiye.com/campus/detail?jobAdId=311168286",
    "prospect": "avoid",
    "why": "教培。覆盖再高也加不了出口，三年锁进错误人才池。"
  },
  {
    "id": "p-三七互娱-海外市场营销",
    "bucket": "pending",
    "company": "三七互娱",
    "title": "海外市场营销",
    "city": "待核",
    "track": "待归类:游戏与内容",
    "channel": "—",
    "url": "https://app.mokahr.com/campus-recruitment/37/58016?locale=zh-CN#/job/f34b9af8-acca-4cf1-8615-ab6b98eaea89",
    "prospect": "avoid",
    "why": "游戏。行业已从清单整体剔除。"
  },
  {
    "id": "p-字节跳动-行业运营管培生全托管-tiktok-shop",
    "bucket": "pending",
    "company": "字节跳动",
    "companyId": "bytedance",
    "title": "行业运营管培生（全托管） - TikTok Shop",
    "city": "深圳",
    "track": "待归类:互联网与科技",
    "channel": "管培生",
    "url": "https://jobs.bytedance.com/campus",
    "prospect": "avoid",
    "why": "国内互联网平台。互联网 GTM 拼不过市场营销+大厂实习，三年锁进内容池。"
  },
  {
    "id": "p-字节跳动-搜索产品运营-tiktok-shop",
    "bucket": "pending",
    "company": "字节跳动",
    "companyId": "bytedance",
    "title": "搜索产品运营 - TikTok Shop",
    "city": "上海",
    "track": "待归类:互联网与科技",
    "channel": "—",
    "url": "https://jobs.bytedance.com/campus",
    "prospect": "avoid",
    "why": "国内互联网平台。互联网 GTM 拼不过市场营销+大厂实习，三年锁进内容池。"
  },
  {
    "id": "p-三七互娱-海外游戏运营",
    "bucket": "pending",
    "company": "三七互娱",
    "title": "海外游戏运营",
    "city": "待核",
    "track": "待归类:游戏与内容",
    "channel": "—",
    "url": "https://app.mokahr.com/campus-recruitment/37/58016?locale=zh-CN#/job/5300b506-365c-457a-bf61-545452ff39ff",
    "prospect": "avoid",
    "why": "游戏。行业已从清单整体剔除。"
  },
  {
    "id": "p-极兔速递-中东27届管培生申请通道",
    "bucket": "pending",
    "company": "极兔速递",
    "title": "【中东】27届管培生申请通道",
    "city": "利雅得",
    "track": "待归类:跨境服务与物流",
    "channel": "管培生",
    "url": "https://jtexpress.jobs.feishu.cn/478610/m/position/7680837918872750362/detail",
    "prospect": "watch",
    "why": "跨境物流驻中东。驻外窗口有限，只有把客户关系沉淀下来才值钱。"
  },
  {
    "id": "p-阿里巴巴-国际化产品运营",
    "bucket": "pending",
    "company": "阿里巴巴",
    "title": "国际化产品运营",
    "city": "深圳",
    "track": "待归类:互联网与科技",
    "channel": "—",
    "url": "https://campus-talent.alibaba.com/campus/position/detail?id=199907800034",
    "prospect": "avoid",
    "why": "国内互联网国际化岗。英专没有专业壁垒，不作为主攻。"
  },
  {
    "id": "p-小红书-2027校招rednote全球内容运营-global-content-operations",
    "bucket": "pending",
    "company": "小红书",
    "title": "【2027校招】rednote全球内容运营/Global Content Operations",
    "city": "上海",
    "track": "待归类:互联网与科技",
    "channel": "—",
    "url": "https://job.xiaohongshu.com/campus/position?positionId=22000",
    "prospect": "avoid",
    "why": "国内互联网平台。互联网 GTM 拼不过市场营销+大厂实习，三年锁进内容池。"
  },
  {
    "id": "p-新东方深圳学校-27届校招天津国际-规划师管培生j66134",
    "bucket": "pending",
    "company": "新东方深圳学校",
    "title": "【27届校招】天津国际——规划师管培生(J66134)",
    "city": "天津",
    "track": "待归类:品牌与新消费",
    "channel": "管培生",
    "url": "https://xdf.zhiye.com/campus/detail?jobAdId=311168302",
    "prospect": "avoid",
    "why": "教培。覆盖再高也加不了出口，三年锁进错误人才池。"
  },
  {
    "id": "p-快手-海外用户增长运营",
    "bucket": "pending",
    "company": "快手",
    "title": "海外用户增长运营",
    "city": "北京",
    "track": "待归类:互联网与科技",
    "channel": "—",
    "url": "https://campus.kuaishou.cn#/campus/jobDetail?positionId=f35c54d8bf4e4b68abedd87c4bc00598",
    "note": "关键技能需补足",
    "prospect": "avoid",
    "why": "国内互联网平台。互联网 GTM 拼不过市场营销+大厂实习，三年锁进内容池。"
  }
];
