(() => {
  'use strict';
  const now = '2026-09-11T12:00:00.000Z';
  const day = '2026-09-11';

  function job(row) {
    const duties = (row.duties || []).map((d) => `${d.title}（${d.pct}）：${d.what}`).join(' ');
    const req = (row.requirements || []).join('；');
    const description = [
      row.headline,
      duties,
      req ? `任职要求：${req}。` : '',
      row.watch ? `要注意：${row.watch}` : '',
      '英专看板按官网校招口径拆岗；投递前请打开官方校招页确认届别、HC 与是否仍开放。',
    ].filter(Boolean).join('');
    return {
      id: row.id,
      company: row.company,
      title: row.title,
      city: row.city,
      graduationYear: '2027',
      roleFamily: row.roleFamily,
      skills: row.skills || ['英语'],
      languages: ['英语'],
      experienceKeywords: row.experienceKeywords || ['海外', '市场', '内容'],
      preferenceTags: row.preferenceTags || ['国际业务', '出海'],
      riskTags: row.riskTags || [],
      watch: row.watch || '',
      source: '英专看板编辑拆岗',
      sourceType: 'official',
      sourceChannel: 'yingzhuan',
      sourceChannelLabel: '英专专项拆岗',
      sourceUrl: row.sourceUrl,
      verification: '英专看板按官网校招JD拆岗 · 投递前请回官网确认是否仍开放',
      publishedAt: day,
      deadline: '',
      discoveredAt: now,
      description,
      jobDescription: duties,
      jobRequirements: req,
      status: '推荐',
      candidateFit: {
        warnings: [],
        strengths: ['英语工作语言'],
        penalty: 0,
        bonus: 0,
        major: {
          verdict: '匹配',
          label: '英语可作为工作语言',
          evidence: row.eligibility || ['英语工作语言', '本科可投', '招聘对象：2027届'],
        },
        responsibility: {
          verdict: '匹配',
          technical: [],
          business: (row.duties || []).map((d) => d.title),
        },
        hardRequirements: [],
        eligibilityEvidence: row.eligibility || ['招聘对象：2027届', '本科可投', '英语工作语言'],
      },
    };
  }

  window.YINGZHUAN_JOBS = [
    job({
      id: 'yingzhuan-ugreen-brand',
      company: '绿联科技',
      title: '海外品牌推广（英语）',
      city: '深圳',
      roleFamily: ['品牌运营', '内容运营', '海外运营'],
      skills: ['英语', '内容运营', 'KOL'],
      experienceKeywords: ['海外', '内容', '品牌', '营销', '社媒'],
      sourceUrl: 'https://www.ugreen.com/pages/recruitment',
      watch: 'HC 按语种拆，招满即止。英语岗对手是小语种+留学。不要和安克渠道重复占两个配件运营位。',
      headline: '数码周边出海。海外品牌/内容岗把英语或小语种写成工作语言，专业卡得比安克品牌松。',
      eligibility: ['招聘对象：2027届', '本科，英语书面+口头无障碍', '英语工作语言'],
      requirements: ['本科，英语书面+口头无障碍', '小语种或留学加分', '沟通、谈判、一点数据意识'],
      duties: [
        { title: '红人与社媒', pct: '40%', what: 'YouTube / Instagram / TikTok 找符合品类的 KOL，谈合作、盯素材和 ROI。英语邮件是日常。' },
        { title: '媒体 PR', pct: '30%', what: '垂类和综合媒体测样、关系维护，英文 pitch 和新闻稿。' },
        { title: '内容与卖点', pct: '20%', what: '产品卖点、评测提纲、多语言说明书协同。' },
        { title: '效果复盘', pct: '10%', what: '曝光、互动、转化表。' },
      ],
    }),
    job({
      id: 'yingzhuan-baseus-sales',
      company: '倍思科技',
      title: '海外销售专员',
      city: '深圳 / 长沙',
      roleFamily: ['海外业务', '国际商务'],
      skills: ['英语', 'Excel', '沟通'],
      experienceKeywords: ['海外', '客户', '订单', '市场'],
      sourceUrl: 'https://hr.baseus.com',
      watch: '第一年是销售助理不是内容。管培「倍星生」和海外销售不要混投同一叙事。',
      headline: '充电和消费电子配件出海。海外销售/商务要六级以上英语，市场专业优先但不卡死。',
      eligibility: ['招聘对象：2027届', '本科可投', '英语听说读写，六级以上'],
      requirements: ['本科，市场/工商优先但不卡死', '英语听说读写，六级以上，小语种加分', '抗压、Office'],
      duties: [
        { title: '区域开拓与客户', pct: '35%', what: '协助经理开拓区域、维护客户和终端。英语对接海外客户。' },
        { title: '订单与合同', pct: '25%', what: '订单、合同存档、交期确认。' },
        { title: '数据与报表', pct: '25%', what: '销量、库存、终端报表。Excel 日常。' },
        { title: '终端与助销', pct: '15%', what: '终端管理、助销活动。' },
      ],
    }),
    job({
      id: 'yingzhuan-tplink-mkt',
      company: 'TP-Link 联洲国际',
      title: '海外市场推广',
      city: '深圳',
      roleFamily: ['品牌营销', '海外运营', '产品营销'],
      skills: ['英语', '内容运营', '市场分析'],
      experienceKeywords: ['海外', '市场', '内容', '营销'],
      sourceUrl: 'https://www.tp-link.com/us/about-us/careers/',
      watch: '联洲和普联可同时投。驻外是加分项也是筛选器。市场岗对手有国贸。',
      headline: '网络设备出海。英语工作语言，和海外公司/经销商对齐 campaign 与物料。',
      eligibility: ['招聘对象：2027届', '本科可投', '英语工作语言'],
      requirements: ['本科', '英语工作语言', '接受出差或驻外加分', '市场/国贸优先但不卡死'],
      duties: [
        { title: '区域市场推广', pct: '45%', what: '和海外公司/经销商对齐 campaign、物料、零售门店活动。英语协同。' },
        { title: '内容与物料', pct: '30%', what: '卖点、手册、社媒和零售物料的多语言版本。' },
        { title: '效果与竞品', pct: '25%', what: '活动效果、竞品在当地渠道的动作。' },
      ],
    }),
    job({
      id: 'yingzhuan-netease-loc',
      company: '网易游戏',
      title: '海外发行运营',
      city: '广州 / 杭州',
      roleFamily: ['内容运营', '海外运营', '用户运营'],
      skills: ['英语', '内容运营', '文案'],
      experienceKeywords: ['海外', '内容', '用户', '社区', '游戏'],
      preferenceTags: ['国际业务', '跨文化'],
      sourceUrl: 'https://game.campus.163.com',
      watch: '通过期望偏低。简历要有一款海外游戏的用户观察，不要只写专四专八。',
      headline: '海外发行与社区。UI/剧情/活动文案的英文本地化，以及 Discord / Reddit 玩家原声。',
      eligibility: ['招聘对象：2027届', '本科，英语/翻译/新闻优先', '英语工作语言'],
      requirements: ['本科，英语/翻译/新闻优先', '有游戏理解，玩过目标品类', '每人最多投 2 岗'],
      duties: [
        { title: '文本与调性', pct: '40%', what: 'UI、剧情、活动文案、社区公告的英文写作，不是对照翻译。' },
        { title: '海外社区', pct: '30%', what: 'Discord / Reddit / 官方论坛，读玩家、回帖、把原声结构化给策划。' },
        { title: '发行协同', pct: '20%', what: '和发行、市场对齐版本卖点和地区合规。' },
        { title: '玩家洞察', pct: '10%', what: '把差评和讨论收成产品结论。' },
      ],
    }),
    job({
      id: 'yingzhuan-unilever-uflp',
      company: '联合利华',
      title: 'UFLP 市场管培',
      city: '上海 / 合肥',
      roleFamily: ['品牌运营', '市场营销'],
      skills: ['英语', '沟通', '市场分析'],
      experienceKeywords: ['品牌', '市场', '项目', '领导力'],
      preferenceTags: ['跨文化'],
      sourceUrl: 'https://www.unilever.com.cn/careers/',
      watch: '通过期望仍低于出海语言岗。没快消实习不要占主志愿。合肥供应链和上海品牌不是同一岗。',
      headline: 'UFLP 2027。英语面试，日常大量中文生意回顾。比宝洁、欧莱雅略好进，仍是彩票。',
      eligibility: ['2026.8–2027.7 毕业', '本科可投', '英语面试'],
      requirements: ['2026.8–2027.7 毕业，中国籍含港澳台', '英语面试', '领导力，专业不限偏商科'],
      duties: [
        { title: '品牌与增长', pct: '50%', what: '清扬/多芬等品牌的战役协助、生意回顾。英语面试，日常中文。' },
        { title: '市场执行', pct: '30%', what: '物料、活动、电商页面。' },
        { title: '轮岗与职能', pct: '20%', what: '可能轮到销售或供应链（合肥）。' },
      ],
    }),
    job({
      id: 'yingzhuan-shokz-mkt',
      company: '韶音科技',
      title: '海外市场 / 品牌校招',
      city: '深圳',
      roleFamily: ['品牌营销', '海外运营', '产品营销'],
      skills: ['英语', '内容运营', '市场分析'],
      experienceKeywords: ['海外', '内容', '市场', '品牌'],
      sourceUrl: 'https://www.shokz.com.cn/pages/campus',
      watch: 'HC 少。岗位以官网实时为准。不要和安克渠道重复占两个硬件运营志愿。',
      headline: '骨传导耳机出海。英语工作语言，海外市场与内容协同。体量小于安克，竞争也小一档。',
      eligibility: ['招聘对象：2027届', '本科可投', '英语工作语言'],
      requirements: ['本科', '英语工作语言', '对运动耳机和音频出海感兴趣'],
      duties: [
        { title: '海外市场与内容', pct: '70%', what: '运动耳机出海市场的内容和渠道协同，英语工作语言。' },
        { title: '跨部门上市支持', pct: '30%', what: '物料、区域同步。' },
      ],
    }),
    job({
      id: 'yingzhuan-dahua-mkt',
      company: '大华股份',
      title: '海外市场营销管培',
      city: '杭州 / 驻外',
      roleFamily: ['海外业务', '市场营销'],
      skills: ['英语', 'Excel', '沟通'],
      experienceKeywords: ['海外', '客户', '市场', '渠道'],
      sourceUrl: 'https://job.dahuatech.com/campus',
      watch: '理工+小语种更吃香。第一年是渠道和订收回，不是写稿。不接受驻外就不要投。',
      headline: '安防出海。2027 海外营销中心在招分销销售、市场、商务。英语/小语种工作语言，要接受出差或常驻。',
      eligibility: ['招聘对象：2027届', '本科，专业不限', 'CET-4/6，英语或小语种可作工作语言'],
      requirements: ['本科，专业不限，理工+小语种优先', 'CET-4/6，英语或小语种可作工作语言', '接受出差或常驻'],
      duties: [
        { title: '代理商与客户', pct: '35%', what: '海外分销客户管理、竞争洞察、开拓渠道。英语对接。' },
        { title: '市场活动', pct: '25%', what: '策划当地市场活动，抬品牌。展会密度高。' },
        { title: '订收回与进销存', pct: '20%', what: '订单、回款、库存分析。Excel 日常。' },
        { title: '驻外执行', pct: '20%', what: '出差或常驻子公司。' },
      ],
    }),
    job({
      id: 'yingzhuan-ecovacs-sales',
      company: '科沃斯',
      title: '全球销售校招生',
      city: '苏州',
      roleFamily: ['海外业务', '跨境电商', '国际商务'],
      skills: ['英语', 'Excel', '电商'],
      experienceKeywords: ['海外', '销售', '电商', '市场'],
      sourceUrl: 'https://campus.ecovacs.cn',
      watch: '日韩德法西等语种经常比英语更稀缺。跨境电商方向要会看广告后台。',
      headline: '家用机器人出海。校招全球销售、跨境电商、市场营销。英语是对接工具，活在渠道和零售。',
      eligibility: ['招聘对象：2027届', '本科可投', '英语工作语言'],
      requirements: ['本科，英语工作语言', '小语种加分', '可接受苏州入职'],
      duties: [
        { title: '海外销售', pct: '40%', what: '区域客户、零售和经销商。英语对接欧美。' },
        { title: '跨境电商', pct: '25%', what: '亚马逊等平台运营协助、广告和页面。英文 listing。' },
        { title: '市场协同', pct: '20%', what: '和海外市场对齐卖点、物料、门店形象。' },
        { title: '数据', pct: '15%', what: '销量、份额、活动效果。' },
      ],
    }),
    job({
      id: 'yingzhuan-dji-sales',
      company: '大疆创新',
      title: '海外销售 / 市场（拓疆者）',
      city: '深圳',
      roleFamily: ['海外业务', '市场营销'],
      skills: ['英语', '沟通', '市场分析'],
      experienceKeywords: ['海外', '销售', '市场', '硬件'],
      sourceUrl: 'https://apply.careers.dji.com/campus-recruitment/dji/143359?locale=zh-CN',
      watch: '通过期望低。没理工或硬件实习，不要占主志愿。和宝洁是同一类名气陷阱。',
      headline: '2027 拓疆者。海外销售/市场要英语，但校招画像是理工。英语流利只是面试环节。',
      eligibility: ['招聘对象：2027届', '本科，理工优先', '英语可作为工作语言'],
      requirements: ['本科，理工优先', '英语可作为工作语言', '接受出差'],
      duties: [
        { title: '海外销售', pct: '45%', what: '区域渠道、客户、数字。英语对接，产品是无人机和影像。' },
        { title: '市场支持', pct: '25%', what: '上市、物料、展会。英文物料。' },
        { title: '英文面试环节', pct: '15%', what: '英语工作语言会出现在面试。' },
        { title: '跨部门', pct: '15%', what: '和产品、供应链对齐一个 SKU。' },
      ],
    }),
    job({
      id: 'yingzhuan-youdao-content',
      company: '网易有道',
      title: '英语教研 / 内容',
      city: '北京 / 杭州',
      roleFamily: ['内容运营', '教研'],
      skills: ['英语', '文案', '内容运营'],
      experienceKeywords: ['内容', '教研', '写作', '课程'],
      preferenceTags: ['跨文化'],
      sourceUrl: 'https://hr.163.com/campus',
      watch: '覆盖会被拉高，不要看成和传音同一档主攻。双减之后 HC 和晋升都更窄。当 offer 保险。',
      headline: '英语教研和内容是英专覆盖最高的岗之一。出口和教培景气度把优先级压低。',
      eligibility: ['招聘对象：2027届', '本科，英语/翻译/对外汉语相关优先', '专八或同等'],
      requirements: ['本科，英语/翻译/对外汉语相关优先', '专八或同等', '能接受教培节奏'],
      duties: [
        { title: '教研与题目', pct: '45%', what: '课程、题目、解析、口语脚本。专四专八训练直接能用。' },
        { title: '内容生产', pct: '30%', what: '图文、视频脚本、词典/翻译相关内容。英文写作。' },
        { title: '教研协同', pct: '15%', what: '和产品、主讲对齐一课的目标。' },
        { title: '效果', pct: '10%', what: '完课、正确率、用户反馈。' },
      ],
    }),
    job({
      id: 'yingzhuan-insta360-kol',
      company: '影石创新',
      title: '海外内容 / KOL',
      city: '深圳',
      roleFamily: ['内容运营', '品牌运营', '海外运营'],
      skills: ['英语', '内容运营', 'KOL'],
      experienceKeywords: ['海外', '内容', '品牌', '营销', '社媒'],
      sourceUrl: 'https://www.insta360.com',
      watch: 'HC 少，留学和作品集对手密。品牌研究岗常写硕士。不要和绿联、韶音重复三个内容志愿。',
      headline: '全景/运动相机出海。海外内容、KOL、品牌研究把英语当工作语言，专业卡得比安克品牌松。',
      eligibility: ['招聘对象：2027届', '本科，英语书面+口头无障碍', '英语工作语言'],
      requirements: ['本科，英语书面+口头无障碍', '对影像/运动内容感兴趣', '作品或社媒实习加分'],
      duties: [
        { title: '达人合作', pct: '40%', what: '北美/欧洲 YouTube、TikTok 找创作者，谈合作、盯素材和发布。英语对接。' },
        { title: '内容与卖点', pct: '30%', what: '全景/运动相机的英文评测提纲、社媒系列、产品故事。' },
        { title: '社区与活动', pct: '20%', what: '和海外创作者社区、线下拍摄活动协同。' },
        { title: '效果复盘', pct: '10%', what: '曝光、互动、转化。第一年填表。' },
      ],
    }),
    job({
      id: 'yingzhuan-ctrip-ops',
      company: '携程集团',
      title: '海外运营',
      city: '上海 / 北京',
      roleFamily: ['海外运营', '内容运营', '用户运营'],
      skills: ['英语', '内容运营', '沟通'],
      experienceKeywords: ['海外', '内容', '运营', '目的地'],
      preferenceTags: ['国际业务', '跨文化'],
      sourceUrl: 'https://careers.ctrip.com',
      watch: '部分岗靠近客服升级。留学生和小语种会把英语本科挤到后面。',
      headline: '2027 秋招综合类明确适配语言。海外目的地运营、商家、内容能用上专业。',
      eligibility: ['招聘对象：2027届', '本科可投', '英语或小语种可作为工作语言'],
      requirements: ['2027 届本科及以上', '英语或小语种可作为工作语言', '专业不限，语言类适配'],
      duties: [
        { title: '目的地运营', pct: '40%', what: '海外目的地的产品、内容和商家协同。英语是生产资料。' },
        { title: '内容', pct: '25%', what: '目的地故事、攻略、活动页。英文写作。' },
        { title: '商家与供给', pct: '20%', what: '和海外酒店/玩乐商家沟通。英文商务沟通。' },
        { title: '用户问题升级', pct: '15%', what: '部分岗靠近客服升级，处理英文投诉。' },
      ],
    }),
  ];

  window.YINGZHUAN_META = {
    绿联科技: { fullName: '深圳市绿联科技股份有限公司', scale: '1000-9999人', nature: '创业板上市公司', tags: ['数码周边', '出海'], watch: 'HC 按语种拆，招满即止。英语岗对手是小语种+留学。不要和安克渠道重复占两个配件运营位。' },
    倍思科技: { fullName: '深圳市倍思科技有限公司', scale: '1000-9999人', nature: '民营企业', tags: ['消费电子', '出海'], watch: '第一年是销售助理不是内容。管培「倍星生」和海外销售不要混投同一叙事。' },
    'TP-Link 联洲国际': { fullName: 'TP-Link 联洲国际', scale: '10000人以上', nature: '民营企业', tags: ['网络设备', '出海'], watch: '联洲和普联可同时投。驻外是加分项也是筛选器。市场岗对手有国贸。' },
    网易游戏: { fullName: '网易游戏互娱', scale: '10000人以上', nature: '上市公司', tags: ['游戏', '出海'], watch: '通过期望偏低。简历要有一款海外游戏的用户观察，不要只写专四专八。' },
    联合利华: { fullName: '联合利华（中国）有限公司', scale: '10000人以上', nature: '外企', tags: ['快消', '品牌'], watch: '通过期望仍低于出海语言岗。没快消实习不要占主志愿。' },
    韶音科技: { fullName: '韶音科技（深圳）有限公司', scale: '1000-9999人', nature: '民营企业', tags: ['音频', '出海'], watch: 'HC 少。岗位以官网实时为准。' },
    大华股份: { fullName: '浙江大华技术股份有限公司', scale: '10000人以上', nature: '上市公司', tags: ['安防', '出海'], watch: '理工+小语种更吃香。第一年是渠道和订收回，不是写稿。不接受驻外就不要投。' },
    科沃斯: { fullName: '科沃斯机器人股份有限公司', scale: '10000人以上', nature: '上市公司', tags: ['家用机器人', '出海'], watch: '日韩德法西等语种经常比英语更稀缺。跨境电商方向要会看广告后台。' },
    大疆创新: { fullName: '深圳市大疆创新科技有限公司', scale: '10000人以上', nature: '民营企业', tags: ['无人机', '影像'], watch: '通过期望低。没理工或硬件实习，不要占主志愿。和宝洁是同一类名气陷阱。' },
    网易有道: { fullName: '网易有道信息技术（北京）有限公司', scale: '1000-9999人', nature: '上市公司子公司', tags: ['教育', '内容'], watch: '覆盖会被拉高，不要看成和传音同一档主攻。双减之后 HC 和晋升都更窄。' },
    影石创新: { fullName: '影石创新科技股份有限公司', scale: '1000-9999人', nature: '科创板上市公司', tags: ['影像', '出海'], watch: 'HC 少，留学和作品集对手密。不要和绿联、韶音重复三个内容志愿。' },
    携程集团: { fullName: '携程集团', scale: '10000人以上', nature: '上市公司', tags: ['酒旅', '出海'], watch: '部分岗靠近客服升级。留学生和小语种会把英语本科挤到后面。' },
  };
})();
